# Default values for fo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

partner: graduate
fqdn: etda-go

image:
  repository: harbor.dsrd.libraries.psu.edu/library/etda-workflow
  tag: 45
  pullPolicy: IfNotPresent
  imagePullSecrets: dsrd-dockerhub

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10000m" 
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
  hosts:
    - host: chart-example.local
      paths: ["/"]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # limits:
  #   memory: 1024Mi
  requests:
    memory: 256Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

env: development

rails:
  environment: production

# PVC for explore and workflow data
persistence:
  enabled: true
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

webaccess:
  enabled: true
  image: harbor.dsrd.libraries.psu.edu/public/apache-docker-webaccess:v3.0.4

certmanager:
  enabled: false
  issuer:
    name: letsencrypt-prod-route53
    kind: ClusterIssuer
  # secretName: ""
  # commonName: ""
  dnsNames: []
  challenge:
    type: dns01
    provider: route53

redis:
  generatePassword: true
  enabled: true
  persistence:
    enabled: true
    storageClass: nfs-client
  master:
    persistence:
      enabled: false
  cluster:
    enabled: false

mysql:
  enabled: true
  username: etda
  database: etda
  replicas: 1
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 1Gi
# mariadb:
#   db:
#     user: etda
#     name: etda_workfow
#   enabled: true
#   image:
#     tag: 10.3.14
#   persistence:
#     storageClass: nfs-client
#     enabled: true

global:
  vault:
    enabled: false
    mountPath: auth/kubernetes
    address: https://vault.dsrd.libraries.psu.edu:8200
    path: secret/data/etd/dev/workflow
    role: etd
    # serviceAccountName: vault-auth

healthcheck:
  readinessProbe:
    initialDelaySeconds: 25
    periodSeconds: 5
    failureThreshold: 3
    path: /healthcheck/all
  livenessProbe:
    path: /healthcheck/all
    initialDelaySeconds: 25
    periodSeconds: 5
    failureThreshold: 3
  enabled: false
