
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: etda-workflow
  namespace: argocd
spec:
  destination:
    namespace: prometheus-operator
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: git@github.com:psu-stewardship/etda_workflow-config.git
    targetRevision: HEAD
    path: chart
    helm:
      values: |
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
