apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: etda-workflow
  namespace: argocd
spec:
  destination:
    namespace: prometheus-operator
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:psu-stewardship/etda-workflow-config.git
    targetRevision: HEAD
    path: chart
    helm:
      values:
        global:
          vault:
            mountPath: auth/k8s-dsrd-dev
            enabled: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
