{{- $fullName := include "chart.fullname" . -}}
{{- if .Values.mod_oidc.enabled }}
---
apiVersion: v1
data:
 vhost.conf: |-
    <VirtualHost _default_:443>

    LogFormat "{ \
    \"@timestamp\":\"%{%FT%T%z}t\", \
    \"client_ip\":\"%a\", \
    \"client_port\":\"%{remote}p\", \
    \"server_ip\":\"%A\", \
    \"X-Forwarded-For\":\"%{X-Forwarded-For}i\", \
    \"user\":\"%u\", \
    \"REMOTE_USER\":\"%{REMOTE_USER}i\", \
    \"JSESSIONID\":\"%{JSESSIONID}C\", \
    \"pid\":\"%p\", \
    \"protocol\":\"%H\", \
    \"http_method\":\"%m\", \
    \"vhost\":\"%{Host}i\", \
    \"service_port\":\"%p\", \
    \"path\":\"%U\", \
    \"query_string\":\"%q\", \
    \"referer\":\"%{Referer}i\", \
    \"user_agent\":\"%{User-agent}i\", \
    \"response_code\":\"%>s\", \
    \"response_location\":\"%{Location}o\", \
    \"Content-Type\":\"%{Content-Type}o\", \
    \"bytes_in\":\"%I\", \
    \"bytes_out\":\"%O\", \
    \"keepalive\":\"%X\", \
    \"duration_micros\":\"%D\" \
    }" json

    RequestHeader set X-Forwarded-Proto "https"

    <LocationMatch / >
        AuthType openid-connect
        Require all granted

        RequestHeader unset HTTP_REMOTE_USER 
    </LocationMatch>

    ProxyPass       /oidc !

    ProxyPreserveHost On

    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/

    <LocationMatch "/login">
        AuthType openid-connect
        Require valid-user
    </LocationMatch>

    <Location /oidc>
        AuthType openid-connect
        Require valid-user
    </Location>

    DocumentRoot /var/www/html

    ErrorLog /proc/self/fd/1
    CustomLog /proc/self/fd/1 json

    SSLEngine on

    SSLCertificateFile	/etc/ssl/certs/cert.crt
    SSLCertificateKeyFile /etc/ssl/private/key.key

    SSLCertificateChainFile /etc/apache2/cosign-ca/InCommonSHA2Chain.pem

    #   CertificatertData +StrictRequire
    <FilesMatch "\.(cgi|shtml|phtml|php)$">
        SSLOptions +StdEnvVars
    </FilesMatch>
    <Directory /usr/lib/cgi-bin>
        SSLOptions +StdEnvVars
    </Directory>

    </VirtualHost>
kind: ConfigMap
metadata:
  name: {{ $fullName }}-webaccess
{{- end }}
