{{- range .Values.ingress.tls }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .secretName }}
spec:
  dnsNames:
  {{- range .hosts }}
  - {{ . }}
  {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-route53
  secretName: {{ .secretName }}
{{- end }}