---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .secretName }}
spec:
  dnsNames:
  - {{ .Values.fqdn }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-route53
  secretName: {{ .Values.fqdn }}