{{- if .Values.certmanager.enabled }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.fqdn }}
spec:
  dnsNames:
  - {{ .Values.fqdn }}
  issuerRef:
    kind: {{ .Values.certmanager.issuer.kind }}
    name: {{ .Values.certmanager.issuer.name }}
  secretName: {{ .Values.fqdn }}
{{- end }}