{{- if .Values.certmanager.enabled }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.certmanager.commonName | default (index .Values.ingress.hosts 0).host }}
spec:
  secretName: {{ .Values.certmanager.secretName | default (index .Values.ingress.tls 0).secretName }}
  issuerRef:
    {{- if eq .Values.certmanager.issuer.kind "ClusterIssuer" }}
    kind: ClusterIssuer
    {{- end }}
    name: {{ .Values.certmanager.issuer.name }}
  dnsNames:
  {{- range .Values.certmanager.dnsNames }}
    - {{ .}}
  {{- end }}
{{- end}}
