{{- $fullName := include "chart.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if .Values.global.vault.enabled }}
        {{- include "vault.annotations" . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 10000
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: vault-token
          emptyDir:
            medium: Memory
        - name: vault-config
          configMap:
            name: {{ $fullName }}-vault
            items:
            - key: env.env
              path: env.env
            - key: vault-agent-config.hcl
              path: vault-agent-config.hcl
        {{- if .Values.mod_oidc.enabled }}
        - name: webaccess-config
          configMap:
            name: {{ $fullName }}-webaccess
        - name: tls
          secret:
            secretName: {{ .Values.fqdn }}
        {{- end }}
        - name: etda-workflow-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ $fullName }}-workflow
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: etda-explore-data
         {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ $fullName }}-explore
         {{- else }}
            emptyDir: {}
         {{- end }}
      {{- if .Values.image.imagePullSecrets}}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
      {{- end }}
      {{- if .Values.global.vault.enabled }}
      serviceAccountName: {{ .Values.global.vault.role }}
      {{- end }}
      containers:
      {{- if .Values.mod_oidc.enabled }}
        - name: {{ .Chart.Name }}-webaccess
          image: {{ .Values.mod_oidc.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: webaccess-config
              mountPath: /etc/apache2/sites-enabled/vhost.conf
              subPath: vhost.conf
            - name: tls
              mountPath: /etc/ssl/certs/cert.crt
              subPath: tls.crt
            - name: tls
              mountPath: /etc/ssl/private/key.key
              subPath: tls.key
          ports:
            - name: http-wa
              containerPort: 80
              protocol: TCP
            - name: https-wa
              containerPort: 443
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            limits:
              cpu: 100m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 1024Mi
      {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{- if .Values.imageName }}{{ .Values.imageName }}{{- else}}{{ .Values.image.repository }}:{{ .Values.image.tag }}{{- end}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DD_ENV
              value: {{ .Values.env }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- if .Values.global.vault.enabled }}
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
            - name: VAULT_PATH
              value: {{ .Values.global.vault.path }}
            - name: VAULT_ADDR
              value: {{ .Values.global.vault.address }}
            {{- end }}
            - name: RAILS_ENV
              value: {{ .Values.rails.environment }}
            - name: PARTNER
              value: {{ .Values.partner }}
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            {{- if .Values.redis.generatePassword }}
            - name: REDIS_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: "{{ $fullName }}-redis"
                  key: REDIS_PASSWORD
            {{- end }}
            {{- if .Values.mysql.enabled }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ $fullName }}-mysql"
                  key: PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ $fullName }}-mysql"
                  key: USER
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "{{ $fullName }}-mysql"
                  key: DATABASE
            - name: MYSQL_HOST
              value: {{ $fullName }}-mysql-master
            {{- end }}
            {{- if .Values.redis.enabled }}
            {{- if .Values.redis.password }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
            {{- end }}
            - name: REDIS_HOST
              value: {{ $fullName }}-redis
            {{- end }}
          volumeMounts:
            - name: shared-data
              mountPath: /secrets
            - name: vault-token
              mountPath: /vault
            - name: etda-workflow-data
              mountPath: /etda_workflow/workflow_data_files
            - name: etda-explore-data
              mountPath: /etda_workflow/explore_data_files
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            periodSeconds: {{ .Values.healthcheck.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.healthcheck.livenessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.healthcheck.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.healthcheck.livenessProbe.path }}
              port: http
          readinessProbe:
            periodSeconds: {{ .Values.healthcheck.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.healthcheck.readinessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.healthcheck.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.healthcheck.readinessProbe.path }}
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
