apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: etda-workflow-circle
  namespace: argocd
spec:
  destination:
    namespace: etda-workflow-circle
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:psu-stewardship/etda-workflow-config.git
    targetRevision: HEAD
    path: chart
    helm:
     values: |
        global:
          vault:
            mountPath: auth/k8s-dsrd-dev
            enabled: true
            path: secret/data/app/etda_workflow/dev
            role: etda-workflow-dev
        image:
          tag: 1438ed828eb41875e9813212aaade73243db0952
          repository: harbor.dsrd.libraries.psu.edu/library/etda-workflow
        fqdn: etda-workflow-circle.dsrd.libraries.psu.edu
        serviceAccount:
          name: etda-workflow-dev
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
