apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: etda-workflow-datadog
  namespace: argocd
spec:
  destination:
    namespace: etda-workflow-datadog
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:psu-stewardship/etda-workflow-config.git
    targetRevision: HEAD
    path: chart
    helm:
     values: |
        global:
          vault:
            mountPath: auth/k8s-dsrd-dev
            enabled: true
            path: secret/data/app/etda_workflow/dev
            role: etda-workflow-dev
        vault:
          mountPath: auth/k8s-dsrd-dev
        image:
          tag: ec584211bc16176a93b2007f457d40113f85f3cf
          repository: harbor.dsrd.libraries.psu.edu/library/etda-workflow
        fqdn: etda-workflow-datadog.dsrd.libraries.psu.edu
        serviceAccount:
          name: etda-workflow-dev
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
