apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: etda-workflow-fix-docker2
  namespace: argocd
spec:
  destination:
    namespace: etda-workflow-fix-docker2
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:psu-stewardship/etda-workflow-config.git
    targetRevision: HEAD
    path: chart
    helm:
     values: |
        global:
          vault:
            mountPath: auth/k8s-dsrd-dev
            enabled: true
            path: secret/app/etda_workflow/dev
            role: etda-workflow-dev
        image:
          tag: 1371
        fqdn: submit-etda-fix-docker2.dsrd.libraries.psu.edu
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
