apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: etda-workflow-main
  namespace: argocd
spec:
  destination:
    namespace: etda-workflow-main
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:psu-stewardship/etda-workflow-config.git
    targetRevision: HEAD
    path: chart
    helm:
     values: |
        global:
          vault:
            mountPath: auth/k8s-dsrd-dev
            enabled: true
            path: secret/data/app/etda_workflow/dev
            role: etda-workflow-dev
        vault:
          mountPath: auth/k8s-dsrd-dev
        image:
          tag: 0d4eb6f45c42cbcb6a6f553413131e6c06fb7f5a
          repository: harbor.k8s.libraries.psu.edu/library/etda-workflow
        fqdn: etda-workflow-main.dev.k8s.libraries.psu.edu
        env: main
        serviceAccount:
          name: etda-workflow-dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
