apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: etda-workflow-qa
  namespace: argocd
spec:
  destination:
    namespace: etda-workflow-qa
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:psu-stewardship/etda-workflow-config.git
    targetRevision: HEAD
    path: chart
    helm:
     values: |
        ingressroute:
          middlewares:
          - name: psu-ip-whitelist
            namespace: traefik
        global:
          vault:
            mountPath: auth/k8s-dsrd-dev
            enabled: true
            path: secret/data/app/etda_workflow/qa
            role: etda-workflow-qa
        vault:
          mountPath: auth/k8s-dsrd-dev
        mysql:
          replicas: 2
        image:
          tag: 652ce75d38abe459f2d0a713a5b4c98ac2eaa009
          repository: harbor.dsrd.libraries.psu.edu/library/etda-workflow
        fqdn: etda-workflow-qa.dev.k8s.libraries.psu.edu
        serviceAccount:
          name: etda-workflow-qa
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
