apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: etda-workflow-qa
  namespace: argocd
spec:
  destination:
    namespace: etda-workflow-qa
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:psu-stewardship/etda-workflow-config.git
    targetRevision: HEAD
    path: chart
    helm:
     values: |
        ingressroute:
          middlewares:
          - name: psu-ip-whitelist
            namespace: traefik
        global:
          vault:
            mountPath: auth/k8s-dsrd-dev
            enabled: true
            path: secret/data/app/etda_workflow/qa
            role: etda-workflow-qa
        vault:
          mountPath: auth/k8s-dsrd-dev
        mysql:
          replicas: 1
        image:
          tag: 7da0c0d43b184e3014a82f7b648323288e57a301
          repository: harbor.k8s.libraries.psu.edu/library/etda-workflow
        fqdn: etda-workflow-qa.dev.k8s.libraries.psu.edu
        serviceAccount:
          name: etda-workflow-qa
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
