apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: etda-workflow-qa
  namespace: argocd
spec:
  destination:
    namespace: etda-workflow-qa
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:psu-stewardship/etda-workflow-config.git
    targetRevision: HEAD
    path: chart
    helm:
     values: |
        global:
          vault:
            mountPath: auth/k8s-dsrd-dev
            enabled: true
            path: secret/data/app/etda_workflow/qa
            role: etda-workflow-qa
        vault:
          mountPath: auth/k8s-dsrd-dev
        image:
          tag: 3e5e9bc83c3fa8f98d85190a2fecb0fccf8c4b82
          repository: harbor.dsrd.libraries.psu.edu/library/etda-workflow
        fqdn: etda-workflow-qa.dsrd.libraries.psu.edu
        serviceAccount:
          name: etda-workflow-qa
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
