apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: etda-workflow-oidc-simplified
  namespace: argocd
spec:
  destination:
    namespace: etda-workflow-oidc-simplified
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:psu-stewardship/etda-workflow-config.git
    targetRevision: oidc
    path: chart
    helm:
     values: |
        webaccess:
          image: harbor.k8s.libraries.psu.edu/public/apache-docker-webaccess:v4.0.1
        global:
          vault:
            mountPath: auth/k8s-dsrd-dev
            enabled: true
            path: secret/data/app/etda_workflow/dev
            role: etda-workflow-dev
        vault:
          mountPath: auth/k8s-dsrd-dev
        image:
          tag: b9fe0ebd19a64802d6ac661ab939b60d41c7f779
          repository: harbor.k8s.libraries.psu.edu/library/etda-workflow
        fqdn: etda-workflow-oidc-simplified.dev.k8s.libraries.psu.edu
        env: oidc-simplified
        serviceAccount:
          name: etda-workflow-dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
