apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: etda-workflow-ruby-2-6-5
  namespace: argocd
spec:
  destination:
    namespace: etda-workflow-ruby-2-6-5
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:psu-stewardship/etda-workflow-config.git
    targetRevision: HEAD
    path: chart
    helm:
     values: |
        global:
          vault:
            mountPath: auth/k8s-dsrd-dev
            enabled: true
            path: secret/data/app/etda_workflow/dev
            role: etda-workflow-dev
        vault:
          mountPath: auth/k8s-dsrd-dev
        image:
          tag: 08d6f8dc03c01da0219f47e1f670b9e2f510ad11
          repository: harbor.dsrd.libraries.psu.edu/library/etda-workflow
        fqdn: etda-workflow-ruby-2-6-5.dev.k8s.libraries.psu.edu
        env: ruby-2-6-5
        serviceAccount:
          name: etda-workflow-dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
